name: Build and Analyze with SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # Use Windows for .NET Framework support

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0'  # Keep .NET SDK installed, but note you're still targeting .NET Framework

    - name: Restore dependencies
      run: dotnet restore MusicPlayerApp.sln

    - name: Clean Solution
      run: dotnet clean MusicPlayerApp.sln

    - name: Build Solution
      run: dotnet build MusicPlayerApp.sln --configuration Release

    - name: Run SonarCloud Analysis (Begin)
      uses: SonarSource/sonarcloud-github-action@v1
      with:
        sonar-project-key: "Kavana179_simple-music-player-app-in-c-sharp"
        sonar-org: "kavana179"
        sonar-host-url: "https://sonarcloud.io"
        sonar-login: ${{ secrets.SONAR_TOKEN }}

    - name: Run Tests
      run: |
        dotnet test MusicPlayerApp.sln --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"

    - name: Run SonarCloud Analysis (End)
      uses: SonarSource/sonarcloud-github-action@v1
      with:
        sonar-project-key: "Kavana179_simple-music-player-app-in-c-sharp"
        sonar-org: "kavana179"
        sonar-host-url: "https://sonarcloud.io"
        sonar-login: ${{ secrets.SONAR_TOKEN }}
        sonar-scanner-args: "-Dsonar.coverageReportPaths=test-results.trx"
