name: Build and Analyze with SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # Ensure that Windows runner is used

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0'  # Use .NET SDK, but for .NET Framework, the SDK itself is not required

    - name: Restore dependencies
      run: dotnet restore MusicPlayerApp.sln  # Restore dependencies

    - name: Clean Solution
      run: dotnet clean MusicPlayerApp.sln  # Clean solution

    - name: Build Solution
      run: dotnet build MusicPlayerApp.sln --configuration Release  # Build the solution

    - name: Run SonarCloud Analysis (Begin)
      uses: SonarSource/sonarcloud-github-action@v1
      with:
        sonar-project-key: "Kavana179_simple-music-player-app-in-c-sharp"
        sonar-org: "kavana179"
        sonar-host-url: "https://sonarcloud.io"
        sonar-login: ${{ secrets.SONAR_TOKEN }}

    - name: Run Tests
      run: |
        dotnet test MusicPlayerApp.sln --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"  # Run tests

    - name: Run SonarCloud Analysis (End)
      uses: SonarSource/sonarcloud-github-action@v1
      with:
        sonar-project-key: "Kavana179_simple-music-player-app-in-c-sharp"
        sonar-org: "kavana179"
        sonar-host-url: "https://sonarcloud.io"
        sonar-login: ${{ secrets.SONAR_TOKEN }}
        sonar-scanner-args: "-Dsonar.coverageReportPaths=test-results.trx"  # End analysis
